# Generated by Django 3.1.7 on 2021-07-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
                ('year', models.CharField(max_length=4, verbose_name='Ano')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangovehiclesapp.vehiclemanufacturer', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='VehicleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangovehiclesapp.vehiclemodel', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Versão',
                'verbose_name_plural': 'Versões',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=10, verbose_name='Placa')),
                ('color', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cor')),
                ('type_fuel', models.CharField(blank=True, choices=[('ET', 'Etanol'), ('DS', 'Diesel'), ('GS', 'Gasolina'), ('GN', 'Gás Natural'), ('FX', 'Fléx'), ('FG', 'Fléx/GNV')], max_length=2, null=True, verbose_name='Combustível')),
                ('renavam', models.CharField(blank=True, max_length=254, null=True, verbose_name='Renavam')),
                ('chassi', models.CharField(blank=True, max_length=254, null=True, verbose_name='Chassi')),
                ('category', models.CharField(blank=True, max_length=254, null=True, verbose_name='Categoria')),
                ('power', models.CharField(blank=True, max_length=254, null=True, verbose_name='Potência')),
                ('displacement', models.CharField(blank=True, max_length=254, null=True, verbose_name='Cilindrada')),
                ('gross_weight', models.FloatField(blank=True, null=True, verbose_name='Peso Bruto')),
                ('engine', models.CharField(blank=True, max_length=254, null=True, verbose_name='Motor')),
                ('axles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Eixos')),
                ('capacity', models.CharField(blank=True, max_length=254, null=True, verbose_name='Capacidade')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('photo', models.ImageField(upload_to='', verbose_name='Foto')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangovehiclesapp.vehicleversion', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
